### PR TITLE
Avocado wallet styling.

### PR DESCRIPTION
**Pull request by Git-Grobe**
Hello!
 I wanted to share this customized version of my styling of the AVO web wallet.  It's a simple "Avocado" theme, I hope you enjoy it as much as I do!

1. Using the pre-existing Avocado media files , I Added a link on index.html for a cool little 32px wide and 32 px high (avocado-icon.png) favicon icon for the web browser tab. 

2. Made the text box around the wallet circular and changed the colors to match the pre-existing Avocado Network media files.

### CODE REVIEW

**Comment by peter-evans** [comment]
Hello.
Thank you for this PR. It's a fun styling!

I'm happy to offer you a separate bounty for this work. The task that you have submitted this work to is for a DApp using AVO, not a styling of the wallet. The size of the bounty also reflects the fact that creating a DApp requires a lot of work. Either I can create a new issue on GitHub with a bounty for you to submit this work to, or you can just let me know your Ethereum address and I will directly send you a bounty from the pool. Let me know which you prefer.

**Comment by Git-Grobe** [comment]
Hello,

I apologize for submitting it incorrectly, I had a lot fun contributing and
would definitely be happy in collecting a separate bounty at this address:

 0xb285861A8d33c18E6e5614C9A3FCe324B71999Ee

Thank you!

I will create a DApp and re-submit!!





I z

**Comment by peter-evans** [comment]
No worries.
I noticed that someone provided some feedback on telegram about the wallet not fitting on the screen properly. I agree that maybe the sizing needs adjusting a bit. I'll leave this PR open if you would like to update it.

If you want to create a DApp for the bounty task please read the task description and discuss your idea and design for the DApp before you start. Thanks.

**Comment by Git-Grobe** [comment]
I re-adjusted some code to provide better sizing, I'm glad to get the sizing feedback, this adjustment looks a lot cleaner and allows easier interface! Let me know what you think! Thanks

**Comment by peter-evans** [comment]
Thank you.
I've sent you a bounty.

**Comment by Git-Grobe** [comment]
Awesome! Thanks so much! Glad that I can contribute!

**Pull request merged**
